AWSTemplateFormatVersion: 2010-09-09
Description: >
  Create a VPC with subnets

Parameters:
  ProjectName:
    Description: Specify the name of the project
    Type: String
    Default: alerzopay
  VpcCidr:
    Description: The cidr range of the VPC
    Type: String
    Default: 10.10.0.0/16
  PublicSubnet1Cidr:
    Description: Cidr range of public subnet 1
    Type: String
    Default: 10.10.1.0/24
  PublicSubnet2Cidr:
    Description: Cidr range of public subnet 2
    Type: String
    Default: 10.10.10.0/24
  PublicSubnet3Cidr:
    Description: Cidr range of public subnet 2
    Type: String
    Default: 10.10.20.0/24
  PrivateSubnet1Cidr:
    Description: Cidr range of Private subnet 1
    Type: String
    Default: 10.10.30.0/24
  PrivateSubnet2Cidr:
    Description: Cidr range of Private subnet 2
    Type: String
    Default: 10.10.40.0/24
  PrivateSubnet3Cidr:
    Description: Cidr range of Private subnet 2
    Type: String
    Default: 10.10.50.0/24
  PrivateSubnet4Cidr:
    Description: Cidr for range wema integration
    Type: String
    Default: 10.10.27.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: True
      EnableDnsSupport: True
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-VPC
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, Fn::GetAZs: ""]
      MapPublicIpOnLaunch: True
      CidrBlock: !Ref PublicSubnet1Cidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PublicSubnet1
  
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, Fn::GetAZs: ""]
      MapPublicIpOnLaunch: True
      CidrBlock: !Ref PublicSubnet2Cidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PublicSubnet2

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, Fn::GetAZs: ""]
      MapPublicIpOnLaunch: True
      CidrBlock: !Ref PublicSubnet3Cidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PublicSubnet3

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, Fn::GetAZs: ""]
      MapPublicIpOnLaunch: False
      CidrBlock: !Ref PrivateSubnet1Cidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, Fn::GetAZs: ""]
      MapPublicIpOnLaunch: False
      CidrBlock: !Ref PrivateSubnet2Cidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PrivateSubnet2

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, Fn::GetAZs: ""]
      MapPublicIpOnLaunch: False
      CidrBlock: !Ref PrivateSubnet3Cidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PrivateSubnet3

  PrivateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, Fn::GetAZs: ""]
      MapPublicIpOnLaunch: False
      CidrBlock: !Ref PrivateSubnet4Cidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PrivateSubnet4
        - Key: Use Case
          Value: This subnet is added for WEMA integration
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-IGW
  
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-Public-RT

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0

  PublicRouteTableSubnetAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicRouteTableSubnetAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PublicRouteTableSubnetAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet3

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PrivateRT
  
  PrivateRouteTableSubnetAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

  PrivateRouteTableSubnetAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet2

  PrivateRouteTableSubnetAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet3

  PrivateRouteTableSubnetAssociation4:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet4

      
Outputs:
  VpcID:
    Description: ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${ProjectName}-VPC
  
  VpcCidrBlock:
    Description: Return the Cidr of the VPC
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub ${ProjectName}-VpcCidr

  PublicSubnet1ID:
    Description: ID of PublicSubnet1
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet1ID

  PublicSubnet1Cidr:
    Description: Cidr Block of PublicSubnet1
    Value: !Ref PublicSubnet1Cidr
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet1Cidir

  PublicSubnet1AZ:
    Description: AZ of PublicSubnet1
    Value: !GetAtt PublicSubnet1.AvailabilityZone
    Export:
      Name: !Sub ${ProjectName}PublicSubnet1-AZ

  PublicSubnet2ID:
    Description: ID of PublicSubnet2
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet2ID

  PublicSubnet2Cidr:
    Description: Cidr Block of PublicSubnet2
    Value: !Ref PublicSubnet2Cidr
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet2Cidr

  PublicSubnet2AZ:
    Description: AZ of PublicSubnet2
    Value: !GetAtt PublicSubnet2.AvailabilityZone
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet2-AZ

  PublicSubnet3ID:
    Description: ID of PublicSubnet3
    Value: !Ref PublicSubnet3
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet3ID

  PublicSubnet3Cidr:
    Description: Cidr Block of PublicSubnet3
    Value: !Ref PublicSubnet3Cidr
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet3Cidr

  PublicSubnet3AZ:
    Description: AZ of PublicSubnet3
    Value: !GetAtt PublicSubnet3.AvailabilityZone
    Export:
      Name: !Sub ${ProjectName}-PublicSubnet3-AZ

  PublicSubnets:
    Description: Return a list of IDs of the App Subnets
    Value:
      Fn::Join: [",", [ !Ref PublicSubnet1, !Ref PublicSubnet2, !Ref PublicSubnet3 ]]
    Export:
      Name: !Sub ${ProjectName}-PublicSubnets

  PrivateSubnet1ID:
    Description: ID of Private Subnet 1
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet1ID

  PrivateSubnet1Cidr:
    Description: Cidr Block of PrivateSubnet1
    Value: !Ref PrivateSubnet1Cidr
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet1Cidr

  PrivateSubnet1AZ:
    Description: AZ of Private Subnet 1
    Value: !GetAtt PrivateSubnet1.AvailabilityZone
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet1-AZ

  PrivateSubnet2ID:
    Description: ID of Private Subnet 2
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet2ID

  PrivateSubnet2Cidr:
    Description: Cidr Block of PrivateSubnet2
    Value: !Ref PrivateSubnet2Cidr
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet2Cidr

  PrivateSubnet2AZ:
    Description: AZ of Private Subnet 2
    Value: !GetAtt PrivateSubnet2.AvailabilityZone
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet2-AZ

  PrivateSubnet3ID:
    Description: ID of Private Subnet 3
    Value: !Ref PrivateSubnet3
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet3ID

  PrivateSubnet4Cidr:
    Description: Cidr Block of PrivateSubnet4. Added for WEMA integration
    Value: !Ref PrivateSubnet4Cidr
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet4Cidr

  PrivateSubnet4ID:
    Description: ID of Private Subnet 4. Added for WEMA integration
    Value: !Ref PrivateSubnet4
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet4ID

  PrivateSubnet3Cidr:
    Description: Cidr Block of PrivateSubnet3
    Value: !Ref PrivateSubnet3Cidr
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet3Cidr

  PrivateSubnet3AZ:
    Description: AZ of Private Subnet 3
    Value: !GetAtt PrivateSubnet3.AvailabilityZone
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnet3-AZ
  
  PublicRouteTableID:
    Description: ID of public route table 
    Value: !Ref PublicRouteTable
    Export:
      Name: !Sub ${ProjectName}-PublicRouteTableID

  PrivateRouteTableId:
    Description: ID of PrivateRouteTable
    Value: !Ref PrivateRouteTable
    Export:
      Name: !Sub ${ProjectName}-PrivateRTID

  PrivateSubnets:
    Description: Subnet group for the private subnet
    Value: !Join [",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2, !Ref PrivateSubnet3, !Ref PrivateSubnet4 ]]
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnetGroup
