apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: {{ .Values.svc.selector.app }}-{{ .Values.environment }}
